services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: my-postgres-db
    environment:
      POSTGRES_DB: digitalLogistics
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d digitalLogistics"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
      - spring-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # Jenkins
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: my-jenkins
    privileged: true
    user: root
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - spring-network
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

  # SonarQube
  sonarqube:
    image: sonarqube:community
    container_name: my-sonarqube
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: admin
      SONAR_JDBC_PASSWORD: admin123
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    networks:
      - spring-network
    restart: unless-stopped

  # ================== ELK STACK ==================


#  filebeat:
#    image: docker.elastic.co/beats/filebeat:8.19.0
#    container_name: my-filebeat
#    user: root
#    depends_on:
#      - logstash
#    volumes:
#      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
#      - ./logs/app.log:/var/logs/app.log:ro
#    command: filebeat -e --strict.perms=false -c /usr/share/filebeat/filebeat.yml
#    networks:
#      - spring-network
#    restart: unless-stopped

volumes:
  postgres_data:
  jenkins_home:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

networks:
  spring-network:
    driver: bridge
